### ISSUE TITLE
http: panic serving 127.0.0.1:44392: reflect: call of reflect.Value.FieldByName on zero Value

### ISSUE THREAD

**Issue by TCB13** [eranyanay/1m-go-websockets#10]
Hello,

I was trying to run the 3rd/4th example, server started fine but at first connection I got:

```
root@debian:~/1m-go-websockets/4_optimize_gobwas# go run server.go epoll.go
2019/04/23 10:05:56 http: panic serving 127.0.0.1:44392: reflect: call of reflect.Value.FieldByName on zero Value
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc420074300)
        /usr/lib/go-1.7/src/net/http/server.go:1491 +0x12a
panic(0x6fb440, 0xc420120520)
        /usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
reflect.flag.mustBe(0x0, 0x19)
        /usr/lib/go-1.7/src/reflect/value.go:201 +0xae
reflect.Value.FieldByName(0x0, 0x0, 0x0, 0x757a6c, 0x5, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/reflect/value.go:794 +0x49
main.websocketFD(0x8d0ae0, 0xc420024058, 0xc420024058)
        /root/1m-go-websockets/4_optimize_gobwas/epoll.go:88 +0x171
main.(*epoll).Add(0xc4200b9040, 0x8d0ae0, 0xc420024058, 0x0, 0x0)
        /root/1m-go-websockets/4_optimize_gobwas/epoll.go:32 +0x6d
main.wsHandler(0x8ce4a0, 0xc42012e410, 0xc4200bc0f0)
        /root/1m-go-websockets/4_optimize_gobwas/server.go:20 +0x96
net/http.HandlerFunc.ServeHTTP(0x786fe8, 0x8ce4a0, 0xc42012e410, 0xc4200bc0f0)
        /usr/lib/go-1.7/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x8ef140, 0x8ce4a0, 0xc42012e410, 0xc4200bc0f0)
        /usr/lib/go-1.7/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420074280, 0x8ce4a0, 0xc42012e410, 0xc4200bc0f0)
        /usr/lib/go-1.7/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420074300, 0x8cec60, 0xc420010800)
        /usr/lib/go-1.7/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/lib/go-1.7/src/net/http/server.go:2293 +0x44d
```

OS: Debian GNU/Linux 9.8 (stretch)
Go: go version go1.7.4 linux/amd64

Any tips? Thank you.

**Comment by TCB13** [comment]
Installing go1.12.4 fixes this.
